background {
  path=$HOME/wallpapers/wallpaper.jpg
}

general {
  font_size=15
  hide_cursor=true
  ignore_empty_input=true
}

input-field {
  size=700,35
  check_color=rgba(0,0,0,0)
  dots_size=1
  dots_text_format=+
  fade_on_empty=false
  fade_timeout=0
  fail_color=rgba(0,0,0,0)
  fail_text=
  font_color=rgb(c7d6dc)
  halign=center
  inner_color=rgba(0,0,0,0)
  outer_color=rgba(0,0,0,0)
  placeholder_text=
  valign=top
}

label {
  halign=right
  text=[$LAYOUT[E,R]]
  valign=top
}
