source = ./hyprbinds.conf
source = ./windowrules.conf

env=JBR_FORCE_WAYLAND,1
env=_JAVA_AWT_WM_NONREPARENTING,1
env=XDG_CURRENT_DESKTOP,Hyprland
env=QT_QPA_PLATFORM,wayland
env=QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env=MOZ_ENABLE_WAYLAND,1

exec-once=wl-paste --watch cliphist store

binds {
  allow_workspace_cycles=true
  workspace_back_and_forth=true
}

cursor {
  inactive_timeout=0.500000
}

decoration {
  shadow {
    color=$base00
  }
  active_opacity=1.000000
  inactive_opacity=0.800000
  rounding=0
}

general {
  border_size=0
  col.active_border=$base0D
  col.inactive_border=$base03
  gaps_in=0
  gaps_out=0
  layout=master
}

group {
  groupbar {
    col.active=$base0D
    col.inactive=$base03
    gaps_in=0
    gaps_out=0
    render_titles=false
    text_color=$base05
  }
  col.border_active=$base0D
  col.border_inactive=$base03
  col.border_locked_active=$base0C
}

input {
  touchpad {
    natural_scroll=true
  }
  follow_mouse=3
  kb_layout=us,ru
  kb_options=grp:win_space_toggle
  repeat_delay=300
  repeat_rate=40
}

misc {
  background_color=$base00
  disable_hyprland_logo=true
  disable_splash_rendering=true
}
