general {
  after_sleep_cmd=hyprctl dispatch 'hl.dsp.dpms({action = "enable" })'
  before_sleep_cmd=loginctl lock-session
  lock_cmd=pidof hyprlock || hyprlock
}

listener {
  on-resume=brightnessctl -r
  on-timeout=brightnessctl -s set 15
  timeout=480
}

listener {
  on-resume=brightnessctl -rd rgb:kbd_backlight
  on-timeout=brightnessctl -sd rgb:kbd_backlight set 0
  timeout=480
}

listener {
  on-timeout=loginctl lock-session
  timeout=600
}

listener {
  on-resume=hyprctl dispatch 'hl.dsp.dpms({action = "enable" })' && brightnessctl -r
  on-timeout=hyprctl dispatch 'hl.dsp.dpms({action = "enable" })'
  timeout=720
}

listener {
  on-timeout=systemctl suspend
  timeout=1800
}
